apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurante-acme-vars
  namespace: fiap
  labels:
    app: restaurante-acme
data:
  PORT: "4080"
  MYSQL_HOST: mysql-svc.fiap
  MYSQL_PORT: "3306"
  MYSQL_USERNAME: developer0101
  MYSQL_PASSWORD: developer0101
  MYSQL_DATABASE: restaurante_acme
  API_ACCESS_KEY: cf0dfe4b4fe039bde4f79d1e2def2aa32d36a6ab32773cff92fdb7833686cef2
  API_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlOYW1lIjoicG9udGFsdGVjaC1yY3MtYXBpLWNsaWVudC1wb2ludGVyIn0.ASugz5QZS757QdNXqzIa2TDn4Wx1znAUBWtdMv4AzdQ
  CHECK_IP_AUTHORIZATION: "false"
  WHITE_LIST_IPS: ""

