apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $K8S_APPLICATION_NAME-secrets
  namespace: $K8S_NAMESPACE
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: $K8S_NAMESPACE/$K8S_APPLICATION_NAME
    - extract:
        key: database/mysql
